feat: support default template config
vuejs/repl pull request #196
Opened 2023-12-25 09:44 UTC by JinweiOS

Related questions #195

2024-01-03 09:01 UTC, yyx990803 requested changes

2024-01-03 09:01 UTC, yyx990803 commented on src/store.ts
> +  defaultWelcomeTpl?: string
```suggestion
  welcomeFileTemplate?: string
```

2024-01-03 09:01 UTC, yyx990803 commented on src/store.ts
> +  defaultSFCTpl?: string
```suggestion
  newSFCTemplate?: string
```

2024-01-04 08:21 UTC, sxzz approved these changes

2024-01-04 08:21 UTC, merged