fix: output toggle button
vuejs/repl pull request #279
Opened 2024-08-26 13:24 UTC by lecepin

- ~~增加嵌入风格，isEmbeddedMode。~~
- mobile 模式下的， Output/Code 的定制透出。
- 修复响应式下的切换按钮不工作问题

2024-08-26 13:29 UTC, lecepin commented
![image](https://github.com/user-attachments/assets/2903c4e0-2ead-4d5f-b7af-de4ac5208b0b)

![image](https://github.com/user-attachments/assets/b8cc7ca5-035c-4295-8d7d-5bdb6c0a4b2a)


嵌入文档等场景使用。

2024-09-03 05:49 UTC, lecepin commented
@sxzz 你好，可以帮忙 CR 下么

2024-09-03 18:15 UTC, sxzz requested changes
The embed mode is hard to generalize and can be easily achieved with style overrides, so it can be removed.

2024-09-07 22:52 UTC, sxzz requested changes

2024-09-07 22:52 UTC, sxzz commented on src/Repl.vue
> +  isEmbedMode?: boolean
As https://github.com/vuejs/repl/pull/279#pullrequestreview-2278144262 said, embed mode can be implemented without any javascript.

2024-09-07 22:52 UTC, sxzz commented on src/Repl.vue
> +  isEmbedMode: false
Remove it

2024-09-07 22:52 UTC, sxzz commented on src/SplitPane.vue
> +
Remove blanks

2024-09-16 06:15 UTC, sxzz approved these changes

2024-09-16 06:16 UTC, merged