feat: support for customize sandbox
vuejs/repl pull request #42
Opened 2022-06-05 06:23 UTC by Blackman99

### Support for customize some sandbox features

* Support customize sandbox head tags, such as `<link ref="stylesheet" href="custom/css/file">`
* Support customize sandbox app import code, such as `import SomePlugin/GlobalComponent from 'customLib'`
* Support customize sandbox app usage code, such as `app.use(SomePlugin)`, `app.component('CompName', GlobalComponent)`

This PR can possibly solve issue: #41

2022-06-26 02:47 UTC, yyx990803 requested changes
I like this, but IMO the API needs some adjustments:

1. These should be merged into a single prop `previewOptions`:

```vue
<Repl
  :previewOptions="{
    headHTML: `...`, // inject to end of head
    bodyHTML: `...`, // inject to end of body, e.g. Teleport targets
    customCode: `import foo from 'xxx'; app.use(foo)`
  }"
/>
```

Note there's no need to separate import statements and app code, since import statements are hoisted can be placed anywhere.

The entire options object can also be provided as a single injection instead of three.

2022-06-26 05:26 UTC, Blackman99 commented
Thanks for api adjustments suggestion. I've changed the origin api to suggested `previewOptions`

But there is still a problem:
If I merge the import code with the app use code (use the `previewOptions.customCode` option), somehow the repl show a error message: Unexpected Identifier which point to the import statement
The error only disappeared when I separate them.

Based on that I've changed the `previewOptions.customCode` to `previewOptions.customCode.importCode` and `previewOptions.customCode.useCode`

Here's my changed commit, in the test/main.ts, has some code I've used to test the feature, using a components lib write by myself: [Casual UI](https://github.com/Blackman99/casual-ui)

2023-06-01 06:57 UTC, fvena commented
Why hasn't this feature been merged yet? I believe it could be very useful. Is there any default feature that allows us to accomplish this?

2023-06-14 07:44 UTC, merged

2023-06-14 08:35 UTC, fvena commented
👏👏👏👏👏🎉🎉🍾🍾🎉🎉

2023-06-16 08:29 UTC, bhabgs commented
如何在编译阶段，就把ui组件给编译了呢？